---
- name: Deploy App
  hosts: app
  become: yes
  tasks:
  - name: Clone latest reddit-monolith
    git:
      repo: 'https://github.com/express42/reddit.git'
      dest: '/home/{{ deploy_user }}/reddit'
      version: 'monolith'
    notify: reload puma

  - name: Bundler install
    bundler:
      state: present
      chdir: '/home/{{ deploy_user }}/reddit'

  handlers:
  - name: reload puma
    systemd:
      daemon_reload: yes
      name: puma
      state: restarted
