---
- name: Pre-Configure App
  become: true
  hosts: all
  tasks:
  - name: App install deps
    apt:
      name:
        - git
        - ruby-full
        - ruby-bundler
        - build-essential
      state: present
