---
- name: App install deps
  apt:
    name: git
    state: present

- name: Add unit file for puma
  template:
    src: puma.service.j2
    dest: /etc/systemd/system/puma.service
  notify: reload puma

- name: Deploy db_config env file from template
  template:
    src: db_config.j2
    dest: "/home/{{ deploy_user }}/db_config"
    owner: "{{ deploy_user }}"
    group: "{{ deploy_user }}"
  notify: reload puma

- name: Enable puma service
  systemd:
    name: puma
    enabled: yes
